name: Laravel Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install npm dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Upload build assets
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "public/build"
          target: "${{ secrets.DEPLOY_PATH }}/public"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            source ~/.nvm/nvm.sh
            cd ${{ secrets.DEPLOY_PATH }}
            git fetch origin main
            git reset --hard origin/main
            git clean -fd
            composer install --no-dev --optimize-autoloader
            rm -rf node_modules
            rm -rf package-lock.json
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
